# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: models/optim/optimizer_config.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#models/optim/optimizer_config.proto\x12\x0cmodels.optim\"\xe3\x01\n\x0fOptimizerConfig\x12\x16\n\x04type\x18\x01 \x01(\t:\x08momentum\x12\x12\n\nlearn_rate\x18\x02 \x01(\x02\x12\x15\n\x08momentum\x18\x03 \x01(\x02:\x03\x30.9\x12\x12\n\nbatch_size\x18\x04 \x01(\x05\x12\x16\n\x0emax_train_iter\x18\x05 \x01(\x05\x12(\n\x19learn_rate_scheduler_type\x18\x06 \x01(\t:\x05\x66ixed\x12\x1e\n\x16learn_rate_decay_steps\x18\x07 \x03(\x05\x12\x17\n\x0flearn_rate_list\x18\x08 \x03(\x02')



_OPTIMIZERCONFIG = DESCRIPTOR.message_types_by_name['OptimizerConfig']
OptimizerConfig = _reflection.GeneratedProtocolMessageType('OptimizerConfig', (_message.Message,), {
  'DESCRIPTOR' : _OPTIMIZERCONFIG,
  '__module__' : 'models.optim.optimizer_config_pb2'
  # @@protoc_insertion_point(class_scope:models.optim.OptimizerConfig)
  })
_sym_db.RegisterMessage(OptimizerConfig)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _OPTIMIZERCONFIG._serialized_start=54
  _OPTIMIZERCONFIG._serialized_end=281
# @@protoc_insertion_point(module_scope)
